"""Initial migration

Revision ID: d7dcb462cc51
Revises: be4f0519c8c1
Create Date: 2026-07-11 04:28:11.248700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7dcb462cc51'
down_revision = 'be4f0519c8c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jsonMapData', sa.Text(), nullable=False),
    sa.Column('aiAdvice', sa.Text(), nullable=False),
    sa.Column('fileName', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Password', sa.Text(), nullable=True))
        batch_op.alter_column('username',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('FileName')
        batch_op.drop_column('JsonMapData')
        batch_op.drop_column('AI_advice')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('AI_advice', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('JsonMapData', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('FileName', sa.TEXT(), nullable=False))
        batch_op.alter_column('username',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('Password')

    op.drop_table('project')
    # ### end Alembic commands ###
